"""Initial migration

Revision ID: 0e7924daabea
Revises: 
Create Date: 2023-12-21 12:10:44.129381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7924daabea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eng', sa.String(length=100), nullable=False),
    sa.Column('pol', sa.String(length=100), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eng', sa.String(length=100), nullable=False),
    sa.Column('pol', sa.String(length=100), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('placement', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('base_words')
    # ### end Alembic commands ###
